version: "3.2"
services:
  zero:
    image: dgraph/dgraph:v21.03.2
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph-20-03
        volume:
          nocopy: true
    ports:
      - 15080:5080
      - 16080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  server:
    image: dgraph/dgraph:v21.03.2
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph-20-03
        volume:
          nocopy: true
      - type: bind
        source: ./tests/resources
        read_only: true
        target: /jwt
        volume:
          nocopy: true
    ports:
      - 18080:8080
      - 19080:9080
    restart: on-failure
    command: dgraph alpha --my=server:7080 --zero=zero:5080  --security "token=; whitelist=0.0.0.0/0;"

volumes:
  dgraph:
